### PR TITLE
Manual Bugfix from Upstream

### LINKED ISSUE #1: bug fix
[`bug-fix`](https://github.com/iFixit/aws-sdk-3.3.2/compare/bug-fix)

### PR DESCRIPTION
**Pull request by djmetzle**
This is a manual intervention to fix a bug that was corrected in a later
version.

CC @soriat @danielbeardsley

Closes #1

### CODE REVIEW

**Comment by soriat** [comment]
CR ⚡️

**Comment by danielbeardsley** [comment]
CR 👍

**Comment by archive64** [comment]
CR 👍

**Comment by djmetzle** [comment]
Mergin it.

**Pull request merged**
